---
- name: "Build an image with the command module"
  hosts: all
  tasks:
    - name: "Creating Policy-Engine.."
      docker_container:
        image: "nginx"
        name:  "ansible_contianer"
        pull:  false
        state: started
        tty: yes
        detach: yes
        log_driver: json-file
        log_opt:
         max-size=25m
         max-file=4
        hostname: "nginx}}"
        ports: "80"
